apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sf-apm-agents.fullname" . }}-cluster
  labels:
    app: {{ template "sf-apm-agents.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "sf-apm-agents.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sf-apm-agents.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: inventory
        image: "{{ .Values.cluster_agent.inventory.image.repository }}:{{ .Values.cluster_agent.inventory.image.tag }}"
        imagePullPolicy: {{ .Values.cluster_agent.inventory.image.pullPolicy }}
        resources:
{{ toYaml .Values.cluster_agent.inventory.resources | indent 12 }}
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
      - name: cluster
        image: "{{ .Values.cluster_agent.cluster_monitoring.image.repository }}:{{ .Values.cluster_agent.cluster_monitoring.image.tag }}"
        imagePullPolicy: {{ .Values.cluster_agent.cluster_monitoring.image.pullPolicy }}
        resources:
{{ toYaml .Values.cluster_agent.cluster_monitoring.resources | indent 12 }}
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
      - name: events
        image: "{{ .Values.cluster_agent.event_metrics.image.repository }}:{{ .Values.cluster_agent.event_metrics.image.tag }}"
        imagePullPolicy: {{ .Values.cluster_agent.event_metrics.image.pullPolicy }}
        resources:
{{ toYaml .Values.cluster_agent.event_metrics.resources | indent 12 }}
        volumeMounts:
          - name: config
            mountPath: /opt/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "sf-apm-agents.fullname" . }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "sf-apm-agents.name" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
{{- if .Values.cluster_agent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cluster_agent.nodeSelector | indent 8 }}
{{- end }}
