rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if create is true, REQUIRED if create is false
  serviceAccountName: default

config:
  # Unique cluster name to add in documents as _tag_cloudName.
  # This is used to create account in APM, this need not be same as actual Kubernets cluster name.
  # Allowed max 32 char, Alphanumeric(a-zA-Z0-9) with dash(-) and underscore(_).
  # REQUIRED field with non empty value
  cluster_name: kubernetes
  # project name label key, value of the label will be added in documents as _tag_projectName
  # projectname_label: snappyflow/projectname
  #
  # application name label key, value of the label will be added in documents as _tag_appName
  # appname_label: snappyflow/appname
  #
  # SnappyFlow APM Elasticsearch Target key copied from APM cloudprofile
  # REQUIRED field with non empty value.
  key: ""
  #
  # SnappyFlow Key for cloud heartbeat and metrics, 
  # If not provided then key used
  # cloud_key: "cluster_key"
  
  # Heartbeat interval
  interval: 300

  # Cluster documents to collect
  node_static: true
  node_compute: true
  node_volume: true
  pod_static: true
  pod_compute: true
  pod_network: false    # Metrics for pod network interfaces
  pod_volume: false     # Metrics for pod volumes
  container_static: true
  container_dynamic: true
  resource: true
  event-stats: true
  service_static: true
  node-storage: true
  storage-stats: true
  node_network: true   # Metrics for node network interfaces

  # Applicable if node_network is true, enable/disable metrics for physical and virtual interfaces
  node_network_physical_interface: true   # Metrics for node network physical interfaces
  node_network_virtual_interface: false   # Metrics for node network virtual interfaces
  
  

# Node Agent
# Per node Plugin Pod
#  container for prometheus poller
#  container for node/pod kubelet monitoring + storage metrics
#  container for fluent-bit logs
node_agent:
  node_metrics:
    image:
      repository: snappyflowml/sfkube-node-metrics
      tag: latest
      pullPolicy: Always
    # if enabled
    configmap:
      # cluster monitoring interval, default is 300 seconds
      interval: 30
      # Tags to be added in cluster metrics document
      #tags: {}
      #target: {}
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
  
  prometheus_poller:
    image:
      repository: snappyflowml/sfkube-node-prom
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    configmap:
      log_dir: /tmp
      interval: 30
      system_interval: 60
    plugin_interval:
      elasticsearch:
        cluster: 300
        node: 300
        index: 900
      nginx:
        default: 300
      mysql:
        default: 300
      kafka:
        default: 300
      jmx:
        default: 300
      kafka-jmx:
        default: 300
      kafka-rest:
        default: 300
      kafka-connect:
        default: 300
      zookeeper-zmx:
        default: 300

  fluentbit:
    enabled: true
    drop_cluster_logs: false
    image:
      fluent_bit:
        repository: snappyflowml/kube-fluent
        tag: latest
      pullPolicy: Always

    podAnnotations: {}

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 10m
      #   memory: 8Mi

  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists


  nodeSelector: {}

forwardmetric:
    # forward metric
    name: sfagentmetric
    enabled: false
    image:
      repository: snappyflowml/sfkube-forward-metric
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8000
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 500Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80

# cluster level plugin Pod
#   Container with cloud heartbeat + cluster document
#   Container for kube events
#   Container for application inventory
cluster_agent:
  inventory:
    image:
      repository: snappyflowml/sfkube-inventory
      tag: latest
      pullPolicy: Always

    ## container resource requests and limits
    ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
  # Cluster monitoring
  cluster_monitoring:
    image:
      repository: snappyflowml/sfkube-cluster
      tag: latest
      pullPolicy: Always
    # if enabled
    configmap:
      # cluster monitoring interval, default is 300 seconds
      interval: 300
      # Tags to be added in cluster metrics document
      #tags: {}
      #target: {}
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi

  event_metrics:
    image:
      repository: snappyflowml/sfkube-events
      tag: latest
      pullPolicy: Always

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi

  tolerations: []

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}


