apiVersion: v2
name: sfapm
description: A Helm chart to deploy snappyflow on Kubernetes
home: https://www.snappyflow.io
type: application
version: 3.1.6
appVersion: 3.1

dependencies:
- name: redis
  version: 0.2.8
  repository: https://snappyflow.github.io/helm-charts/
- name: postgresql
  version: 0.1.2
  repository: https://snappyflow.github.io/helm-charts/
  condition: postgresql.enabled
